name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      run_integration:
        description: "Run integration tests"
        required: false
        default: "false"
        type: choice
        options:
          - "true"
          - "false"
  schedule:
    - cron: "0 6 * * 1" # Mondays 06:00 UTC

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests (exclude integration)
        run: |
          python -m pytest -vv -m "not integration" --maxfail=1

  integration:
    name: Integration Tests (Firecrawl/OpenRouter)
    needs: unit
    if: (github.event_name == 'workflow_dispatch' && github.event.inputs.run_integration == 'true') || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    env:
      FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check secrets availability
        run: |
          if [ -z "$FIRECRAWL_API_KEY" ]; then
            echo "FIRECRAWL_API_KEY is not set. Skipping integration tests."
            exit 1
          fi

      - name: Run integration tests only
        run: |
          python -m pytest -vv -m integration --maxfail=1
